config/routes.rb
Rails.application.routes.draw do

  
  resources :hooks
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
  before_action :set_hook, only: [:show, :edit, :update, :destroy]

  # GET /hooks
  # GET /hooks.json
  def index
#    @hooks = Hook.all
  end

  # GET /hooks/1
  # GET /hooks/1.json
  def show
  end

  # GET /hooks/new
  def new
#    @hook = Hook.new
  end

  # GET /hooks/1/edit
  def edit
  end

  # POST /hooks
  # POST /hooks.json
  def create
#    @hook = Hook.new(hook_params)

#    respond_to do |format|
#      if @hook.save
#        format.html { redirect_to @hook, notice: 'Hook was successfully created.' }
#        format.json { render :show, status: :created, location: @hook }
#      else
#        format.html { render :new }
#        format.json { render json: @hook.errors, status: :unprocessable_entity }
#      end
#    end

    raw_data    = JSON.parse(params.to_json)
    title       = raw_data['data']['item']['title']
    description = 'Report from Rollbar'
    
    baseurl     = ENV['YOUTRACK_BASEURL']
    login       = ENV['YOUTRACK_LOGIN']
    password    = ENV['YOUTRACK_PASSWORD']
    project     = ENV['YOUTRACK_PROJECT']
    
    login = RestClient.post "#{baseurl}/rest/user/login",
      {
        :login    => login,
        :password => password
      }
      
    RestClient.put "#{baseurl}/rest/issue?project=#{project}&summary=#{title}&description=#{description}",
      {},
      {
        :cookies => login.cookies
      }

    render :json => {}, :status => :ok

  end

  # PATCH/PUT /hooks/1
  # PATCH/PUT /hooks/1.json
  def update
#    respond_to do |format|
#      if @hook.update(hook_params)
#        format.html { redirect_to @hook, notice: 'Hook was successfully updated.' }
#        format.json { render :show, status: :ok, location: @hook }
#      else
#        format.html { render :edit }
#        format.json { render json: @hook.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # DELETE /hooks/1
  # DELETE /hooks/1.json
  def destroy
#    @hook.destroy
#    respond_to do |format|
#      format.html { redirect_to hooks_url, notice: 'Hook was successfully destroyed.' }
#      format.json { head :no_content }
#    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hook
#      @hook = Hook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hook_params
      params.permit(:data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hooks_helper.rb
module HooksHelper
end

app/views/hooks/_form.html.erb
<%= form_for(@hook) do |f| %>
  <% if @hook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hook.errors.count, "error") %> prohibited this hook from being saved:</h2>

      <ul>
      <% @hook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hooks/edit.html.erb
<h1>Editing Hook</h1>

<%= render 'form' %>

<%= link_to 'Show', @hook %> |
<%= link_to 'Back', hooks_path %>

app/views/hooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hooks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hooks.each do |hook| %>
      <tr>
        <td><%= link_to 'Show', hook %></td>
        <td><%= link_to 'Edit', edit_hook_path(hook) %></td>
        <td><%= link_to 'Destroy', hook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hook', new_hook_path %>

app/views/hooks/new.html.erb
<h1>New Hook</h1>

<%= render 'form' %>

<%= link_to 'Back', hooks_path %>

app/views/hooks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hook_path(@hook) %> |
<%= link_to 'Back', hooks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RollbarHook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>